config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  get    'signup' => 'readers#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  post '/guest_login', to: 'sessions#guest_login'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'five_star' => 'books#five_star'
  

  # resources :books
  resources :reviews

  resources :readers, except: [:index] do 
    resources :reviews, only: [:index, :show]
  end

  resources :books, only: [:index, :show] do
    resources :reviews, shallow: true
    #shallow gives me [:index, :new, :create]
  end
  get '*all', to: 'books#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # catch-all for incorrect routes, back to the books index, had to exclude active storage, solution from github
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reader.rb
class Reader < ApplicationRecord
    has_many :reviews
    has_many :books, through: :reviews
    has_one_attached :profile_pic

    has_secure_password #validation, .authenticate, .password, .password=

    #validations come from ActiveRecord
    validates :username,:email,  presence: true, uniqueness: true
    validates :password, length: { in: 6..12 }, allow_nil: true
    
    
   
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]
    before_action :set_reader, except: [:new, :create]
    before_action :set_genres
    
    

    def new
        @reader = Reader.new
    end

    #this is the signup action
    def create
       @reader = Reader.new(reader_params)
        if @reader.save 
            session[:reader_id] = @reader.id
            redirect_to reader_path(@reader)
        else
            render :new
        end
    end

    def show
        if !@reader
            redirect_to '/' 
        elsif
            @reader.id == session[:reader_id] 
        else
            redirect_to '/'
        end
    end

    def edit
        
        if !@reader || !@reader.id == session[:reader_id]
            redirect_to '/'
        end
       
    end

    def update
        if @reader.update(reader_params)
            redirect_to reader_path(@reader)
        else
            render :edit
        end
    end

    def destroy
        delete_reader_data
        @reader.destroy
        session.clear
        redirect_to root_path
    end



private

    def reader_params
        params.require(:reader).permit(:username, :password, :first_name, :last_name, :favorite_genre, :favorite_book, :profile_pic, :email)
    end

    def set_reader
        @reader = Reader.find_by_id(params[:id])
    end  
end

app/helpers/readers_helper.rb
module ReadersHelper

    def delete_reader_data
        @reader.reviews.destroy_all
    end
end

app/views/readers/_reader.html.erb
<%= bootstrap_form_with model: @reader, class:"w-75"  do |f| %>

   <%= f.text_field :username%>
   
    <%= f.password_field :password %>
   
    <%= f.email_field :email %>
   
    <%= f.text_field :first_name %>
    
    <%= f.text_field :last_name%>
   
    <%= f.select :favorite_genre, options_for_select(@options), prompt: "Please select"%>
   
    <%= f.text_field :favorite_book%>
    
    <%= f.file_field :profile_pic %> <br><br>

    <%= f.submit %>
<% end %>

app/views/readers/edit.html.erb
<center>
<h1 class="display-4">Update Account</h1>
<%= render "layouts/errors", :object => @reader %>
<div class="border-class">
<%= render 'reader' %><br>
<%= button_to "Delete Reader Profile/Account", reader_path(@reader), method: :delete, data: {confirm: "Are you sure? All reviews will be deleted with your user profile."} %>

</div>
</center>

app/views/readers/new.html.erb
<center>
<h1 class="display-4"> New Account </h1>
<div class="border-class">
<%= render "layouts/errors", :object => @reader %>
<%= render 'reader' %>
</div>
</center>

app/views/readers/show.html.erb
<center>

<h1 class="display-4"><%= @reader.username %></h1>
<%= render 'layouts/profile_pic' %>
<div class="border-class">
    <p class="lead">
    Username: <%= @reader.username%><br>
    Name: <%= @reader.first_name %> <%= @reader.last_name %><br>
    Email: <%= @reader.email %><br>
    Favorite Genre: <%= @reader.favorite_genre%><br>
    Favorite Book: <%= @reader.favorite_book %><br><br>
    
    <%= link_to "edit", edit_reader_path(@reader) %>
    </p><br>
</div>

<hr>


<h3><%= link_to "My Shelf", reader_reviews_path(current_reader) %></h3>
<div class="row">

    <% @reviews = current_reader.reviews %>
    <% @reviews.status.each do |review| %>
    <div class="col-md-2">
        <div class="card" style="width: 10rem;">
        <img src= "<%= review.book.image%>" class="card-img-top" alt="test">
        <div class="card-body">
            <p class="card-text"><%= link_to review.book.title, review_path(review) %><br>
            <em><%= review.status %></em><br>
            <%= link_to "edit", edit_review_path(review) %>
            </p>
        </div>
        </div>
    </div> 
    
    <% end %>
</div>
 <hr />
 </center>

       