config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  get    'signup' => 'readers#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  post '/guest_login', to: 'sessions#guest_login'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'five_star' => 'books#five_star'
  

  # resources :books
  resources :reviews

  resources :readers, except: [:index] do 
    resources :reviews, only: [:index, :show]
  end

  resources :books, only: [:index, :show] do
    resources :reviews, shallow: true
    #shallow gives me [:index, :new, :create]
  end
  get '*all', to: 'books#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # catch-all for incorrect routes, back to the books index, had to exclude active storage, solution from github
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews
    has_many :readers, through: :reviews 
    
    
    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :author, presence: true

    scope :genre, ->{order(:created_at)}
    scope :five_star, ->{joins(:reviews).distinct.where(`reviews.star_rating == "5"`)}
    scope :grouped_reviews, ->{joins(:reviews).group(:reviews, 'books.id')}
    

    def self.get_list(list)
       
        response = RestClient.get("https://api.nytimes.com/svc/books/v3/lists/current/#{list}.json?api-key=#{ENV["KEY"]}")
        # byebug
        list = JSON.parse(response)["results"]
        book_details = (list)["books"]
        #create a Ruby book object with all the info in the books array, use an iterator
        book_details.each do |book|
            
            self.create(title: book["title"], author: book["author"], publisher: book["publisher"], description: book["description"], image: book["book_image"], link_to_purchase: book["amazon_product_url"], genre: (list)["list_name"], published: (list)["published_date"]) 
           
                sleep(1) # sleep for 1 second
            
              
        end
    end
    def self.sorted_books
        genre_order = ["Hardcover Fiction", "Trade Fiction Paperback", "Hardcover Nonfiction", "Mass Market Paperback", "combined-print-and-e-book-fiction", "Hardcover Advice", "Culture", "Hardcover Political Books", "Food and Fitness", "Humor", "Paperback Advice", "Health", "Travel", "Young Adult", "Animals", "Celebrities", "Business Books", "Picture Books", "Hardcover Graphic Books", "Manga", "Sports", "Science", "Religion Spirituality and Faith", "Family", "Race and Civil Rights"]
      
        books_array = self.all.to_a
      
        books_array.sort_by { |book| genre_order.index(book.genre) || genre_order.size }
      end
      
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    before_action :set_book, only: [:show, :edit, :update, :destroy]
    before_action :set_genres, only: [:index]

    def new
        @book = Book.new
    end

    def create
        # byebug
       @book = Book.new(book_params)
        if @book.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    def show
           
        redirect_to books_path if !@book
        
            
    end

    def edit
        if current_reader.id != @book.reader_ids
            redirect_to book_path(@book)
        end
    end

    def update
        @book.update(book_params)
        redirect_to book_path(@book)
    end

    def index
       
    
        
            if params[:title]
                @books = Book.where('title LIKE ?', "%#{params[:title].upcase}%")
                elsif params[:author]
                    @books = Book.where('author LIKE ?', "%#{params[:author]}%")
                elsif params[:genre]
                    @books = Book.where('genre LIKE ?', "#{params[:genre]}")
            else
                
                @books = Book.genre
            end
       
    end

    def five_star
        @books = Book.five_star
        # binding.pry
    end
    
     
    

    def destroy
        @book.destroy
        redirect_to books_path
    end



private

    def book_params
        params.require(:book).permit(:title, :author, :published, :publisher, :description, :genre, :image, :link_to_purchase)
    end

    def set_book
        @book = Book.find_by_id(params[:id])
    end 
end

app/helpers/books_helper.rb
module BooksHelper

    def full_date(date)
        date.to_time.strftime('%b %d, %Y')
    end
end

app/views/books/five_star.html.erb
<center><img src="images/five_star.jpeg" height=17% width=17% ></center><br>
<div class="row">

    <% @books.each do |book| %>

    <div class="col-md-2">    
                <div class="card" style="width: 10rem;">
                <img src= "<%= book.image%>" class="card-img-top" alt="test">
                <div class="card-body">
                    <p class="card-text">
                    <h5><%= link_to book.title, book_path(book) %></h5><br>
                    <%= book.description%><br><br>
                    <%= book.author %><br>
                   <small> <%= book.genre%></small>
                    </p>
                </div>
                </div>
                    
    </div>
   
   <% end %>
</div>

app/views/books/index.html.erb
<center>
<br>
<div class="container">
    <div class="row">
        <div class="col-sm"> 
            <%= form_tag(books_path, method: :get) do %>
            List <%= select_tag(:genre, options_for_select(@options), prompt: "Please select")%>
            <%= submit_tag 'Search', name: nil %>
            <% end %>
            
        </div>
        <div class="col-sm">
            <%= form_tag(books_path, method: :get) do %>
            Author <%= text_field_tag :author, params[:author] %>
            <%= submit_tag 'Search', name: nil %>
            <% end %>
        </div>
        <div class="col-sm">
            <%= form_tag(books_path, method: :get) do %>
            Title <%= text_field_tag :title, params[:title] %>
            <%= submit_tag 'Search', name: nil %>
            <% end %>
        </div>
       
    </div>
</div>
<br>
<br>

<div class="row">

    <% @books.sorted_books.each do |book| %>

       <div class="col-md-2"> 
            <div class="card" style="width: 17rem; border-radius: 5%">
            <a href="<%= book_path(book[:id]) %>">
                <img src= "<%= book.image%>" class="card-img-top" alt="test" style="border-radius: 5%" >
            </a>
            <div class="card-body">
                <p class="card-text"><%= link_to book.title.upcase, book_path(book[:id]) %><br>
                <small><%= book.author %></small><br>
                <%= book.genre %></p>
            </div>
            </div>
        </div>
            
    
        <% end %>
    
</div>
</center>

app/views/books/show.html.erb
<h1 class="display-4"><%= @book.title.upcase %> </h1>

<hr>
<h3><%= link_to "Buy From Amazon" ,  @book.link_to_purchase, :target => "_blank" %></h3><img src="/images/amazon.png" width=5% height=5%><br><br>



<% if  current_reader.reviews.find_by(book_id: params[:id]) == nil %>

    <h3><%= button_to "Add to my shelf", new_book_review_path(@book), method: :get %></h3><br>
<% else %>
  <h3> <%= button_to  "Edit my Review", book_reviews_path(@book) %></h3><br>
    
<% end %> 
<table class="table table-info">
    <tr>
        <th>Author</th> 
        <th>Publisher</th> 
        <th>Published</th>
        <th>Best Seller List</th> 
    </tr>
    <td><%= @book.author %></td> 
    <td><%= @book.publisher %></td>
    <td><%= full_date(@book.published) %></td>
    <td><%= @book.genre %></td>
 </table>   
 <br>
 <% if @book.description? %>
    <blockquote class="blockquote">
        <p class="mb-0"><%= @book.description %></p>   
    </blockquote><br>
<% end %>
    
    <img src= "<%= @book.image %>" height ="329" width "500" ><br>
  
    <center>
<% if @book.reviews.any? %>
    <hr>
    <h3><%= link_to "Reviews", book_reviews_path(@book) %> </h3>
<div class="row"> 
        <% @book.reviews.each do |review| %>
    <div class="col-md-2">    
                <div class="card" style="width: 10rem;">
                <img src= "/images/bf.jpeg" class="card-img-top" alt="test">
                <div class="card-body">
                    <p class="card-text">
                    <%= review.status %><br>
                    <em><%= review.book_review %><em><br>
                    <h2><%= review.star_rating%></h2><br>
                    -<%= review.reader.username %>
                    </p>
                </div>
                </div>
    </div>
        <% end %>
<% end %>
</div>
</center>
<hr>