config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  get    'signup' => 'readers#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  post '/guest_login', to: 'sessions#guest_login'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'five_star' => 'books#five_star'
  

  # resources :books
  resources :reviews

  resources :readers, except: [:index] do 
    resources :reviews, only: [:index, :show]
  end

  resources :books, only: [:index, :show] do
    resources :reviews, shallow: true
    #shallow gives me [:index, :new, :create]
  end
  get '*all', to: 'books#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # catch-all for incorrect routes, back to the books index, had to exclude active storage, solution from github
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :set_review, only: [:edit, :update, :destroy, :show ]
    

    def new
        # byebug
        if params[:book_id]
            @review = Review.new(book_id: params[:book_id])
        else
            @review = Review.new
        end
       
    end
    
    def show
        redirect_to reviews_path if !@review
    end
    
    def create
            @review = Review.new(review_params)
             if @review.save
                redirect_to review_path(@review)
             else
                render 'new'
        end
    end
    
    def index
       @book = Book.find_by(id: params[:book_id])
        if params[:book_id] && !@book.nil?
            @reviews = @book.reviews
        else
            @reader = Reader.find_by(id: params[:reader_id])
            if params[:reader_id] && !@reader.nil?
                @reviews = @reader.reviews.status
            else
                @books = Book.all
                @reviews = @books.grouped_reviews
            end
        end
    end
    
    def edit 
        if current_reader.id != @review.reader_id
            redirect_to review_path(@review)
        end
    end
    
    def update
        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end
    
    def destroy
        @review.destroy
        redirect_to reviews_path
    end
    
    private
    
    def review_params
        params.require(:review).permit(:star_rating, :book_review, :status, :reader_id, :book_id, :id)
    end 
    
    def set_review
        @review = Review.find_by_id(params[:id])
    end
    
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review.html.erb
<%= bootstrap_form_with model: @review do |f| %>
  
  <%= f.hidden_field :reader_id, :value => current_reader.id %> <br><br>

  <%= f.select :status, ["Want to Read", "Currently Reading", "Read"], prompt: "Select a status"  %><br><br>
    <% if params[:book_id] %> 
      <%= f.hidden_field :book_id %> 
    <% else %>
      <%= f.collection_select :book_id, Book.all, :id, :title , prompt: "Select a title"%><br>
      <% end %>
  <%= f.text_area :book_review %><br>

  <%= f.select :star_rating, [5,4,3,2,1, ""], prompt: "Select a star rating" %><br>

  <%= f.submit  value = "Add To Shelf"  %>
<% end %>

app/views/reviews/edit.html.erb
<center>
<h1 class="display-4">Edit Review</h1>
<hr>
<%= render "layouts/errors", :object => @review %>
<div class="border-class">
<%= render 'review' %><br>
<%= button_to "Delete Review", review_path(@review), method: :delete %>
</div>
</center>

app/views/reviews/index.html.erb
<center>
    <% if !@book && !@reader %>
        <% @reviews.each do |book| %>
  
    
        <div class="card-deck" style="width: 15rem;">
            <img src= "<%= book.image%>" class="card-img-top" alt="test"><br>
                <h5><p class="card-text"><%= link_to book.title, book_path(book.id) %></h5>
                <% book.reviews.each do |review| %>
                    <div class="card-body">
                        <figure class="text-end">
                            <blockquote class="blockquote">
                                <p><%= review.book_review %></p>
                            </blockquote>
                            <figcaption class="blockquote-footer"><%= review.reader.try(:username) %></figcaption>
                        </figure>
                 <% end %>
                    </div>
        </div>
        <br>
        
    <% end %>
        </div>

 <br>
    
</center>

        <% else %>
            <div class="row">

                <% @reviews.each do |review| %>

            <div class="col-md-2">     
                    <div class="card" style="width: 10rem;">
                            <img src= "<%= review.book.image%>" class="card-img-top" alt="test">
                            <div class="card-body">
                                <p class="card-text"><%= link_to review.book.title, book_path(review.book.id) %><br>
                                <h3><%= review.star_rating %></h3>
                                <%= review.book_review %><br>
                                -<%= review.reader.try(:username) %><br>
                                <%= review.status %><br>
                                <% if current_reader.id == review.reader_id %>
                                        <%= link_to "edit", edit_review_path(review) %><br>
                                        
                                <% end %>
                                
                            </div>
                            </div>
                </div>
                        
           <% end %> 
        <% end %>
            </div>

app/views/reviews/new.html.erb
<center>

<h1 class="display-4">Book Review</h1> <small>by <%= current_reader.username %></small><br>
<%= render 'layouts/profile_pic' %><br>
    
   <% if params[:book_id] %> 

    <img src="<%= @review.book.image %>" style= height= 150px; width= 150px; >
        <h3><%= @review.book.title %></h3> 
    <% end %>

<%= render "layouts/errors", :object => @review %>
<div class="border-class" style="width: 50%;">
    <%= render 'review' %>
</div>
</center>

app/views/reviews/show.html.erb
<h2><%= link_to @review.book.title, book_path(@review.book.id) %></h2>

<img src= "<%= @review.book.image %>" height="15%", width="15%">
        <hr />
        <p>     
                <div class="card" style="width: 10rem;">
                <img src= "/images/bf.jpeg" class="card-img-top" alt="test">
                <div class="card-body">
                    <p class="card-text">
                        <h3><%= @review.star_rating %></h3>
                        <em><%= @review.book_review %></em>
                        <%= @review.reader.username %><br><br>
                        <%= @review.status %><br>
                        <% if current_reader.id == @review.reader_id %>
                                <%= link_to "edit", edit_review_path %><br>
                                <%= button_to "Delete Review", review_path(@review), method: :delete %>
                        <% end %>
                       </p>
                </div>
                </div>
                    
        </p> 