config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  get    'signup' => 'readers#new'
  get    'login' => 'sessions#new'
  post   'login' => 'sessions#create'
  post '/guest_login', to: 'sessions#guest_login'
  delete 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  get 'five_star' => 'books#five_star'
  

  # resources :books
  resources :reviews

  resources :readers, except: [:index] do 
    resources :reviews, only: [:index, :show]
  end

  resources :books, only: [:index, :show] do
    resources :reviews, shallow: true
    #shallow gives me [:index, :new, :create]
  end
  get '*all', to: 'books#index', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # catch-all for incorrect routes, back to the books index, had to exclude active storage, solution from github
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.each do |error| %>
        <li><h3><%= error.full_message %></h3></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
    
<% if logged_in? %>
            
        <nav class="navbar navbar-expand-lg navbar-light>
        <div class="container-fluid">
            <a class="navbar-brand" <%= link_to "bookface", root_path %></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <h5><a class="nav-link", color <%= link_to "Best Sellers", books_path %></h5>
                </li>
                <li class="nav-item">
                <a class="nav-link" <%= link_to "Profile", current_reader %>
                </li>
                <li class="nav-item">
                <a class="nav-link" <%= link_to "Reviews", reviews_path %>
                </li>
                <li class="nav-item">
                <a class="nav-link"<%= link_to "New Review", new_review_path%>
                </li>
                <li class="nav-item">
                <a class="nav-link"<%= link_to "Five Star", '/five_star'%>
                </li>
                <li class="nav-item">
                <a class="nav-link"<%= link_to "Log out", logout_path, method: "delete"%>
                </li>
            </ul>
            </div>
        </div>
        </nav>  
<% else %>     
   <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">bookface</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" <%= link_to "Log in", login_path %>
                </li>
                <li class="nav-item">
                <a class="nav-link" <%= link_to "Signup", signup_path %>
                </li>
            </ul>
            </div>
        </div>
        </nav>           
            
<% end %>

app/views/layouts/_profile_pic.html.erb
<% if current_reader.profile_pic.attached? %>
    <img src= "<%= (url_for(current_reader.profile_pic)) %>" alt="profile pic" height="250", width="150"><br>
    <% elsif current_reader.omni_pic? %>
        <img src= "<%= (url_for(current_reader.omni_pic)) %>" alt="social pic" height=75px width =75px ><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bf</title>
    <meta charset="utf-8">
    <meta name="google-site-verification" content="5TwoMk7AnzY37Nqq0JVXovZbllWFdMyHD7aiqeYZZns" />

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Merriweather:ital@0;1&family=Work+Sans:wght@400;500;800&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/header' %>
     <% flash.each do |name, msg| -%>
     <%= content_tag :div, msg, class: name %> 
    <% end %>


  </head>

  <body>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    
    <%= yield %>
  </body>
</html>